### ISSUE TITLE
runtime error in training.py - tensor dimension mismatch

### ISSUE THREAD

**Issue by felixsc1** [neuropoly/multiclass-segmentation#2]
I tried running _training.py_ with a training and validation dataset arranged as you nicely described in the pipeline.
Unfortunaltey, I get this rather generic error message below from pytorch. 
What I tried already, googling this error: 
- Setting batch size to 1 didn't help.
- Initially my data was 256x150 pixels per slice, so I cropped it to a square of 150x150. Didn't help.

Any other ideas, or should I provide you with an example dataset?

```
Working on cpu.
Training network...
  0%|          | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "training.py", line 156, in <module>
    output =  net(input)
  File "/home/felix/miniconda3/envs/segmentation/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/felix/Repos/multiclass-segmentation/models.py", line 93, in forward
    x8 = self.up1(x7, x5)
  File "/home/felix/miniconda3/envs/segmentation/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/felix/Repos/multiclass-segmentation/models.py", line 38, in forward
    x = torch.cat([x, y], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 36 and 37 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653194318/work/aten/src/TH/generic/THTensor.cpp:711
```

**Comment by FrancoisPgm** [comment]
Hi, the issue is that the cropping sizes should be multiples of 2^np where np is the number of poolings in the model, which is 3 for the SmallUNet and 4 for the traditionnal UNet. 
It should work with 144x144 squares. 

Thank you for pointing that out, I'll add this detail to the instructions.
